# -*- coding: utf-8 -*-
"""CRUD - Tabla periódica - Git

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nsfvkYNPRLPghKHzEe1O0N2uyy4vpvGe
"""

"""
Sistema CRUD - Tabla Periódica de Elementos Químicos
Autor: [Tu Nombre]
Descripción: Sistema interactivo para gestionar datos de elementos con validación
basada en catálogo oficial IUPAC. Implementa Create, Read, Update, Delete.
"""

# Base de datos inicial
tabla_p = [
    {'elemento': 'Hidrógeno', 'simbolo': 'H', 'numero_atómico': 1, 'masa_atomica': 1.00794},
    {'elemento': 'Helio', 'simbolo': 'He', 'numero_atómico': 2, 'masa_atomica': 4.00260},
    {'elemento': 'Litio', 'simbolo': 'Li', 'numero_atómico': 3, 'masa_atomica': 6.94100}
]

# Catálogos de validación IUPAC
elementos_quimicos = [
    "Hidrógeno", "Helio", "Litio", "Berilio", "Boro", "Carbono", "Nitrógeno", "Oxígeno",
    "Flúor", "Neón", "Sodio", "Magnesio", "Aluminio", "Silicio", "Fósforo", "Azufre",
    "Cloro", "Argón", "Potasio", "Calcio", "Hierro", "Cobre", "Plata", "Oro", "Mercurio",
    "Plomo", "Uranio", "Oganesón"
]

simbolos_quimicos = [
    "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si",
    "P", "S", "Cl", "Ar", "K", "Ca", "Fe", "Cu", "Ag", "Au", "Hg", "Pb", "U", "Og"
]

def mostrar_elementos(tabla):
    """Muestra todos los elementos en formato legible"""
    print('\n---LISTA DE ELEMENTOS---')
    if not tabla:
        print("La tabla está vacía.")
        return
    for i, elem in enumerate(tabla):
        print(f"Elemento #{i+1}:")
        print(f" Nombre: {elem['elemento']}")
        print(f" Símbolo: {elem['simbolo']}")
        print(f" Número Atómico: {elem['numero_atómico']}")
        print(f" Masa Atómica: {elem['masa_atomica']} g/mol")
        print("-" * 30)

def crear_elemento(tabla, elementos_validos, simbolos_validos):
    """Añade nuevo elemento con validación de duplicados y catálogo IUPAC"""
    print("\n--- AGREGAR NUEVO ELEMENTO ---")

    while True:
        nombre = input('Nombre del elemento: ').strip().capitalize()
        if nombre.lower() not in [e.lower() for e in elementos_validos]:
            print(f"Error: '{nombre}' no es un elemento válido. Intente de nuevo.")
        elif any(e['elemento'].lower() == nombre.lower() for e in tabla):
            print(f"Error: '{nombre}' ya existe en la tabla.")
        else:
            break

    while True:
        simbolo = input('Símbolo: ').strip()
        simbolo = simbolo.upper() if len(simbolo) == 1 else simbolo.capitalize()
        if simbolo not in simbolos_validos:
            print(f"Error: '{simbolo}' no es un símbolo válido.")
        elif any(e['simbolo'] == simbolo for e in tabla):
            print(f"Error: Símbolo '{simbolo}' ya existe.")
        else:
            break

    while True:
        try:
            num_atomico = int(input('Número atómico: '))
            if num_atomico <= 0:
                print("Error: Debe ser entero positivo.")
            elif any(e['numero_atómico'] == num_atomico for e in tabla):
                print(f"Error: Número atómico {num_atomico} ya existe.")
            else:
                break
        except ValueError:
            print("Entrada no válida. Ingrese un entero.")

    while True:
        try:
            masa = float(input('Masa atómica: '))
            if masa <= 0:
                print("Error: Debe ser positivo.")
            else:
                break
        except ValueError:
            print("Entrada no válida. Ingrese un número.")

    tabla.append({
        'elemento': nombre,
        'simbolo': simbolo,
        'numero_atómico': num_atomico,
        'masa_atomica': masa
    })
    print(f"\n✓ Elemento '{nombre}' añadido con éxito")

def consultar_por_nombre(tabla):
    """Busca elemento por nombre"""
    nombre = input("Nombre a consultar: ").strip().capitalize()
    for elem in tabla:
        if elem['elemento'] == nombre:
            print(f"\n--- {nombre} ---")
            print(f"Símbolo: {elem['simbolo']}")
            print(f"Número Atómico: {elem['numero_atómico']}")
            print(f"Masa Atómica: {elem['masa_atomica']} g/mol")
            return
    print(f"Error: '{nombre}' no encontrado.")

def eliminar_elemento(tabla):
    """Elimina elemento por nombre con confirmación"""
    nombre = input("Nombre a eliminar: ").strip().capitalize()
    for elem in tabla:
        if elem['elemento'] == nombre:
            confirm = input(f"¿Eliminar {nombre}? (sí/no): ").strip().lower()
            if confirm in ['sí', 'si']:
                tabla.remove(elem)
                print(f"✓ '{nombre}' eliminado.")
            else:
                print("Cancelado.")
            return
    print(f"Error: '{nombre}' no encontrado.")

def menu_principal():
    """Menú interactivo CRUD"""
    while True:
        print("\n=== MENÚ TABLA PERIÓDICA ===")
        print("1. Ver elementos")
        print("2. Agregar elemento")
        print("3. Consultar por nombre")
        print("4. Eliminar elemento")
        print("5. Salir")

        opcion = input("Opción: ").strip()

        if opcion == '1':
            mostrar_elementos(tabla_p)
        elif opcion == '2':
            crear_elemento(tabla_p, elementos_quimicos, simbolos_quimicos)
        elif opcion == '3':
            consultar_por_nombre(tabla_p)
        elif opcion == '4':
            eliminar_elemento(tabla_p)
        elif opcion == '5':
            print("¡Hasta luego!")
            break
        else:
            print("Opción inválida. Intente 1-5.")

if __name__ == "__main__":
    menu_principal()
